#running a sandbox ios-xe router from devnet with ansiblels
#https://devnetsandbox.cisco.com/RM/Diagram/Index/27d9747a-db48-4565-8d44-df318fce37ad?diagramType=Topology
#NOTE :  #use cisco.ios.ios_command , cisco.ios.ios_banner   for ansible >=3 
---
- name: General Config for ios-xe router 
  hosts: routers

  tasks: 

  - name: first run multiple commands on remote router
    ios_command:
      commands:
      - show version
      - show interfaces

  - name:  second run commands that require answering a prompt
    ios_command:
      commands:
        - command: 'clear counters GigabitEthernet1'
          prompt: 'Clear "show interface" counters on this interface \[confirm\]'
          answer: 'y'
        - command: 'clear counters GigabitEthernet2'
          prompt: '[confirm]'
          answer: "\r"

  - name:  then add  banner to router
    ios_banner:
      banner: login
      text: |
        ****hello this is cisco router ios-xe ***
      state: present

  - name: finaly remove the motd banner
    ios_banner:
      banner: motd
      state: absent    
